# Generated by Django 6.1 on 2026-08-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
