# Generated by Django 6.1 on 2026-08-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo_app', '0004_momo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category_images'),
        ),
    ]
