# Generated by Django 6.1 on 2026-08-11 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo_app', '0005_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='momo_app.category'),
        ),
    ]
