# Generated by Django 6.1 on 2026-08-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo_app', '0006_alter_momo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('rating', models.PositiveBigIntegerField()),
                ('order', models.CharField(max_length=250)),
            ],
        ),
    ]
